In [1]:
import numpy as np

### Creating Numpy Array

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
lis = [[4,5,7],[3,8,9]]
arr = np.array(lis)

In [7]:
arr

array([[4, 5, 7],
       [3, 8, 9]])

In [8]:
arr.ndim

2

In [9]:
arr.dtype

dtype('int32')

In [10]:
lis = [[3.0,3.88,8],[7,6.89,9]]
arr = np.array(lis)

In [11]:
arr.dtype

dtype('float64')

### Propertis of npArray

In [12]:
arr 

array([[3.  , 3.88, 8.  ],
       [7.  , 6.89, 9.  ]])

In [13]:
print(arr.shape)

(2, 3)


In [14]:
print(arr.itemsize)

8


In [20]:
arr = np.zeros((3,4))

In [21]:
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
arr = np.ones((5,4), dtype=int)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [26]:
arr = np.eye((5),dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [32]:
arr = np.arange(1,51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [33]:
arr.shape

(50,)

In [34]:
arr.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [35]:
arr = arr.reshape(5,10)

In [36]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [46]:
arr = np.arange(100).reshape(10,10)

In [47]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
arr = np.arange(5,56,5).reshape(1,11)

In [44]:
arr

array([[ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]])

In [64]:
arr = np.random.random((8,3))

In [65]:
arr

array([[0.22582958, 0.88536545, 0.7836639 ],
       [0.31923301, 0.43455888, 0.91402657],
       [0.20737096, 0.41171192, 0.1767441 ],
       [0.75469695, 0.11916115, 0.72258939],
       [0.45824825, 0.10737954, 0.05515293],
       [0.54918049, 0.424254  , 0.23397519],
       [0.79630094, 0.23197237, 0.06293817],
       [0.89953278, 0.39440689, 0.45572002]])

In [69]:
#element wise
arr = arr*100
print(arr)

[[22.582958   88.53654462 78.3663903 ]
 [31.92330051 43.45588821 91.40265698]
 [20.73709587 41.17119214 17.67441041]
 [75.46969498 11.91611525 72.25893868]
 [45.82482456 10.7379536   5.51529349]
 [54.91804879 42.42539989 23.39751928]
 [79.63009448 23.19723657  6.29381736]
 [89.95327787 39.44068903 45.57200159]]


In [70]:
np.round(arr,3)

array([[22.583, 88.537, 78.366],
       [31.923, 43.456, 91.403],
       [20.737, 41.171, 17.674],
       [75.47 , 11.916, 72.259],
       [45.825, 10.738,  5.515],
       [54.918, 42.425, 23.398],
       [79.63 , 23.197,  6.294],
       [89.953, 39.441, 45.572]])

In [55]:
arr = np.random.randint(1,100)

In [56]:
arr

75

In [71]:
arr = np.random.randint(1,100, 72)
print(arr)

[51 55  1 36 99 62 45 12  3 19 35 50 52 37 55 59 73 14 58 31 67 93 40 96
 49 37 62 53 57  9 29 65 55 64 74 83 53 22 64 46 97 81  6 27 33 93 92 26
 42 80 86 10 38 31 70  1 39 10 60 16 65 42 49 15 91 75 84 78 85 25 61 84]


In [72]:
arr.reshape(8,9)

array([[51, 55,  1, 36, 99, 62, 45, 12,  3],
       [19, 35, 50, 52, 37, 55, 59, 73, 14],
       [58, 31, 67, 93, 40, 96, 49, 37, 62],
       [53, 57,  9, 29, 65, 55, 64, 74, 83],
       [53, 22, 64, 46, 97, 81,  6, 27, 33],
       [93, 92, 26, 42, 80, 86, 10, 38, 31],
       [70,  1, 39, 10, 60, 16, 65, 42, 49],
       [15, 91, 75, 84, 78, 85, 25, 61, 84]])

In [73]:
arr= np.linspace(5,50,5)
print(arr)

[ 5.   16.25 27.5  38.75 50.  ]


In [74]:
np.ceil(arr) #next value of array

array([ 5., 17., 28., 39., 50.])

### Mathematical values and functions

In [75]:
np.pi

3.141592653589793

In [76]:
np.sin(45)

0.8509035245341184

In [81]:
arr = np.arange(10,100)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [83]:
arr_sin = np.sin(arr)
print(arr_sin)

[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525  0.83665564
 -0.00885131 -0.8462204  -0.90557836 -0.13235175  0.76255845  0.95637593
  0.27090579 -0.66363388 -0.98803162 -0.40403765  0.55142668  0.99991186
  0.52908269 -0.42818267 -0.99177885 -0.64353813  0.29636858  0.96379539
  0.74511316 -0.15862267 -0.91652155 -0.83177474  0.01770193  0.85090352
  0.90178835  0.12357312 -0.76825466 -0.95375265 -0.26237485  0.67022918
  0.98662759  0.39592515 -0.55878905 -0.99975517 -0.521551    0.43616476
  0.99287265  0.63673801 -0.30481062 -0.96611777 -0.7391807   0.1673557
  0.92002604  0.82682868 -0.02655115 -0.85551998 -0.89792768 -0.11478481
  0.77389068  0.95105465  0.25382336 -0.67677196 -0.98514626 -0.38778164
  0.56610764  0.99952016  0.51397846 -0.44411267 -0.99388865 -0.62988799
  0.31322878  0.96836446  0.73319032 -0.17607562 -0.92345845 -0.82181784
  0.0353983   0.86006941  0.89399666  0.10598751 -0.

In [86]:
arr_log = np.log(arr)
print(arr_log)

[2.30258509 2.39789527 2.48490665 2.56494936 2.63905733 2.7080502
 2.77258872 2.83321334 2.89037176 2.94443898 2.99573227 3.04452244
 3.09104245 3.13549422 3.17805383 3.21887582 3.25809654 3.29583687
 3.33220451 3.36729583 3.40119738 3.4339872  3.4657359  3.49650756
 3.52636052 3.55534806 3.58351894 3.61091791 3.63758616 3.66356165
 3.68887945 3.71357207 3.73766962 3.76120012 3.78418963 3.80666249
 3.8286414  3.8501476  3.87120101 3.8918203  3.91202301 3.93182563
 3.95124372 3.97029191 3.98898405 4.00733319 4.02535169 4.04305127
 4.06044301 4.07753744 4.09434456 4.11087386 4.12713439 4.14313473
 4.15888308 4.17438727 4.18965474 4.20469262 4.21950771 4.2341065
 4.24849524 4.26267988 4.27666612 4.29045944 4.30406509 4.31748811
 4.33073334 4.34380542 4.35670883 4.36944785 4.38202663 4.39444915
 4.40671925 4.41884061 4.4308168  4.44265126 4.4543473  4.46590812
 4.47733681 4.48863637 4.49980967 4.51085951 4.52178858 4.53259949
 4.54329478 4.55387689 4.56434819 4.57471098 4.58496748 4.595119

In [88]:
arr_cos = np.cos(arr)
arr_cos

array([-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
        0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
       -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293,
       -0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
        0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254,
        0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99339038,
        0.6333192 , -0.30902273, -0.96725059, -0.73619272,  0.17171734,
        0.92175127,  0.82433133, -0.03097503, -0.85780309, -0.89

In [89]:
np.sqrt(4)

2.0

In [92]:
arr_sqr = np.sqrt(arr)
print(arr_sqr)

[3.16227766 3.31662479 3.46410162 3.60555128 3.74165739 3.87298335
 4.         4.12310563 4.24264069 4.35889894 4.47213595 4.58257569
 4.69041576 4.79583152 4.89897949 5.         5.09901951 5.19615242
 5.29150262 5.38516481 5.47722558 5.56776436 5.65685425 5.74456265
 5.83095189 5.91607978 6.         6.08276253 6.164414   6.244998
 6.32455532 6.40312424 6.4807407  6.55743852 6.63324958 6.70820393
 6.78232998 6.8556546  6.92820323 7.         7.07106781 7.14142843
 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477 7.54983444
 7.61577311 7.68114575 7.74596669 7.81024968 7.87400787 7.93725393
 8.         8.06225775 8.1240384  8.18535277 8.24621125 8.30662386
 8.36660027 8.42614977 8.48528137 8.54400375 8.60232527 8.66025404
 8.71779789 8.77496439 8.83176087 8.88819442 8.94427191 9.
 9.05538514 9.11043358 9.16515139 9.21954446 9.2736185  9.32737905
 9.38083152 9.43398113 9.48683298 9.53939201 9.59166305 9.64365076
 9.69535971 9.74679434 9.79795897 9.8488578  9.89949494 9.94987437]


### Array Slicing

In [94]:
arr = np.arange(1,16).reshape(3,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [95]:
print(arr[1:4,0:3])   # [row,column]

[[ 6  7  8]
 [11 12 13]]


###  Mathematical Operations

In [96]:
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(a,b, sep ="\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [97]:
print(np.add(a,b))   #add

[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [100]:
print(np.subtract(a,b))      #subtract

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [103]:
#element wise multiplication
print(np.multiply(a,b))

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [104]:
print(np.divide(a,b))

[[0.         0.1        0.18181818]
 [0.25       0.30769231 0.35714286]
 [0.4        0.4375     0.47058824]]


In [106]:
b//a

<ipython-input-106-0dbf865fa61c>:1: RuntimeWarning: divide by zero encountered in floor_divide
  b//a


array([[ 0, 10,  5],
       [ 4,  3,  2],
       [ 2,  2,  2]], dtype=int32)

In [107]:
#matrix multiplication
a.dot(b)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [108]:
print(np.dot(a,b))

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [109]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
a.T    #transpose

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [111]:
b.ravel()

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

### inbuilt functions

In [112]:
a.sort()

In [113]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
arr =np.random.random((8,9))

In [116]:
arr

array([[0.02876592, 0.16946357, 0.08314648, 0.19528562, 0.89705869,
        0.95703159, 0.10833071, 0.94151079, 0.63949723],
       [0.02675676, 0.63057063, 0.70625494, 0.92294152, 0.06396449,
        0.68496436, 0.27071458, 0.41533113, 0.60518846],
       [0.03253578, 0.929167  , 0.56367195, 0.93541675, 0.14988552,
        0.26234525, 0.35688614, 0.63976807, 0.57262514],
       [0.23458649, 0.78389411, 0.08616542, 0.76941408, 0.09912215,
        0.21925607, 0.32482617, 0.86338064, 0.04413637],
       [0.84095389, 0.12852806, 0.70765768, 0.16778682, 0.83850098,
        0.83946933, 0.18903418, 0.08697439, 0.93059657],
       [0.45113987, 0.61554284, 0.26195124, 0.73963982, 0.84869978,
        0.54288181, 0.84487491, 0.39756664, 0.17551811],
       [0.41666017, 0.42481422, 0.0590699 , 0.5347447 , 0.85128821,
        0.74044717, 0.64270816, 0.45344094, 0.64206833],
       [0.4209681 , 0.06366484, 0.27290215, 0.79064961, 0.25509647,
        0.43195212, 0.79220196, 0.64750578, 0.79607196]])

In [117]:
arr.sort()

In [118]:
arr

array([[0.02876592, 0.08314648, 0.10833071, 0.16946357, 0.19528562,
        0.63949723, 0.89705869, 0.94151079, 0.95703159],
       [0.02675676, 0.06396449, 0.27071458, 0.41533113, 0.60518846,
        0.63057063, 0.68496436, 0.70625494, 0.92294152],
       [0.03253578, 0.14988552, 0.26234525, 0.35688614, 0.56367195,
        0.57262514, 0.63976807, 0.929167  , 0.93541675],
       [0.04413637, 0.08616542, 0.09912215, 0.21925607, 0.23458649,
        0.32482617, 0.76941408, 0.78389411, 0.86338064],
       [0.08697439, 0.12852806, 0.16778682, 0.18903418, 0.70765768,
        0.83850098, 0.83946933, 0.84095389, 0.93059657],
       [0.17551811, 0.26195124, 0.39756664, 0.45113987, 0.54288181,
        0.61554284, 0.73963982, 0.84487491, 0.84869978],
       [0.0590699 , 0.41666017, 0.42481422, 0.45344094, 0.5347447 ,
        0.64206833, 0.64270816, 0.74044717, 0.85128821],
       [0.06366484, 0.25509647, 0.27290215, 0.4209681 , 0.43195212,
        0.64750578, 0.79064961, 0.79220196, 0.79607196]])

In [120]:
arr[0:2,0:6]<=5

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

# Pandas

In [130]:
import pandas as pd

In [132]:
df = pd.read_csv('winemag-data_first150k.csv')

In [133]:
df.head()

Unnamed: 0 country                                        description  \
0           0      US  This tremendous 100% varietal wine hails from ...   
1           1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2           2      US  Mac Watson honors the memory of a wine once ma...   
3           3      US  This spent 20 months in 30% new French oak, an...   
4           4  France  This is the top wine from La Bégude, named aft...   

                            designation  points  price        province  \
0                     Martha's Vineyard      96  235.0      California   
1  Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2         Special Selected Late Harvest      96   90.0      California   
3                               Reserve      96   65.0          Oregon   
4                            La Brûlade      95   66.0        Provence   

            region_1           region_2             variety  \
0        Napa Valley               Napa  Cabernet Sauvignon   
1               Toro                NaN       Tinta de Toro   
2     Knights Valley             Sonoma     Sauvignon Blanc   
3  Willamette Valley  Willamette Valley          Pinot Noir   
4             Bandol                NaN  Provence red blend   

                    winery  
0                    Heitz  
1  Bodega Carmen Rodríguez  
2                 Macauley  
3                    Ponzi  
4     Domaine de la Bégude

In [134]:
df.iloc[:,1]

0             US
1          Spain
2             US
3             US
4         France
           ...  
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object

In [138]:
df.loc[:,'country':'variety']

country                                        description  \
0           US  This tremendous 100% varietal wine hails from ...   
1        Spain  Ripe aromas of fig, blackberry and cassis are ...   
2           US  Mac Watson honors the memory of a wine once ma...   
3           US  This spent 20 months in 30% new French oak, an...   
4       France  This is the top wine from La Bégude, named aft...   
...        ...                                                ...   
150925   Italy  Many people feel Fiano represents southern Ita...   
150926  France  Offers an intriguing nose with ginger, lime an...   
150927   Italy  This classic example comes from a cru vineyard...   
150928  France  A perfect salmon shade, with scents of peaches...   
150929   Italy  More Pinot Grigios should taste like this. A r...   

                                 designation  points  price  \
0                          Martha's Vineyard      96  235.0   
1       Carodorum Selección Especial Reserva      96  110.0   
2              Special Selected Late Harvest      96   90.0   
3                                    Reserve      96   65.0   
4                                 La Brûlade      95   66.0   
...                                      ...     ...    ...   
150925                                   NaN      91   20.0   
150926                        Cuvée Prestige      91   27.0   
150927                         Terre di Dora      91   20.0   
150928                       Grand Brut Rosé      90   52.0   
150929                                   NaN      90   15.0   

                  province           region_1           region_2  \
0               California        Napa Valley               Napa   
1           Northern Spain               Toro                NaN   
2               California     Knights Valley             Sonoma   
3                   Oregon  Willamette Valley  Willamette Valley   
4                 Provence             Bandol                NaN   
...                    ...                ...                ...   
150925      Southern Italy  Fiano di Avellino                NaN   
150926           Champagne          Champagne                NaN   
150927      Southern Italy  Fiano di Avellino                NaN   
150928           Champagne          Champagne                NaN   
150929  Northeastern Italy         Alto Adige                NaN   

                   variety  
0       Cabernet Sauvignon  
1            Tinta de Toro  
2          Sauvignon Blanc  
3               Pinot Noir  
4       Provence red blend  
...                    ...  
150925         White Blend  
150926     Champagne Blend  
150927         White Blend  
150928     Champagne Blend  
150929        Pinot Grigio  

[150930 rows x 9 columns]

In [139]:
df.price<100

0         False
1         False
2          True
3          True
4          True
          ...  
150925     True
150926     True
150927     True
150928     True
150929     True
Name: price, Length: 150930, dtype: bool

In [140]:
df.loc[df.price<=100]

Unnamed: 0 country                                        description  \
2                2      US  Mac Watson honors the memory of a wine once ma...   
3                3      US  This spent 20 months in 30% new French oak, an...   
4                4  France  This is the top wine from La Bégude, named aft...   
5                5   Spain  Deep, dense and pure from the opening bell, th...   
6                6   Spain  Slightly gritty black-fruit aromas include a s...   
...            ...     ...                                                ...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150926      150926  France  Offers an intriguing nose with ginger, lime an...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150928      150928  France  A perfect salmon shade, with scents of peaches...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

                          designation  points  price            province  \
2       Special Selected Late Harvest      96   90.0          California   
3                             Reserve      96   65.0              Oregon   
4                          La Brûlade      95   66.0            Provence   
5                           Numanthia      95   73.0      Northern Spain   
6                           San Román      95   65.0      Northern Spain   
...                               ...     ...    ...                 ...   
150925                            NaN      91   20.0      Southern Italy   
150926                 Cuvée Prestige      91   27.0           Champagne   
150927                  Terre di Dora      91   20.0      Southern Italy   
150928                Grand Brut Rosé      90   52.0           Champagne   
150929                            NaN      90   15.0  Northeastern Italy   

                 region_1           region_2             variety  \
2          Knights Valley             Sonoma     Sauvignon Blanc   
3       Willamette Valley  Willamette Valley          Pinot Noir   
4                  Bandol                NaN  Provence red blend   
5                    Toro                NaN       Tinta de Toro   
6                    Toro                NaN       Tinta de Toro   
...                   ...                ...                 ...   
150925  Fiano di Avellino                NaN         White Blend   
150926          Champagne                NaN     Champagne Blend   
150927  Fiano di Avellino                NaN         White Blend   
150928          Champagne                NaN     Champagne Blend   
150929         Alto Adige                NaN        Pinot Grigio   

                       winery  
2                    Macauley  
3                       Ponzi  
4        Domaine de la Bégude  
5                   Numanthia  
6                    Maurodos  
...                       ...  
150925  Feudi di San Gregorio  
150926              H.Germain  
150927              Terredora  
150928                 Gosset  
150929          Alois Lageder  

[133770 rows x 11 columns]

In [141]:
df.loc[(df.price<=100) & (df.country == 'Italy')]

Unnamed: 0 country                                        description  \
10              10   Italy  Elegance, complexity and structure come togeth...   
37              37   Italy  Aromas of forest floor, violet, red berry and ...   
38              38   Italy  This has a charming nose that boasts rose, vio...   
39              39   Italy  This bright, savory wine delivers aromas and f...   
43              43   Italy  Aromas of dark-skinned berry, rose and wild he...   
...            ...     ...                                                ...   
150824      150824   Italy  This 100% Cortese wine has a slight fizz and a...   
150920      150920   Italy  Rich and mature aromas of smoke, earth and her...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

               designation  points  price            province  \
10      Ronco della Chiesa      95   80.0  Northeastern Italy   
37                     NaN      90   29.0             Tuscany   
38                     NaN      90   23.0             Tuscany   
39                 Riserva      90   29.0             Tuscany   
43                 Riserva      90   39.0             Tuscany   
...                    ...     ...    ...                 ...   
150824                 NaN      87   18.0            Piedmont   
150920        Brut Riserva      91   19.0  Northeastern Italy   
150925                 NaN      91   20.0      Southern Italy   
150927       Terre di Dora      91   20.0      Southern Italy   
150929                 NaN      90   15.0  Northeastern Italy   

                            region_1 region_2          variety  \
10                            Collio      NaN         Friulano   
37      Vino Nobile di Montepulciano      NaN       Sangiovese   
38                  Chianti Classico      NaN       Sangiovese   
39                  Chianti Classico      NaN        Red Blend   
43                  Chianti Classico      NaN        Red Blend   
...                              ...      ...              ...   
150824                          Gavi      NaN          Cortese   
150920                        Trento      NaN  Champagne Blend   
150925             Fiano di Avellino      NaN      White Blend   
150927             Fiano di Avellino      NaN      White Blend   
150929                    Alto Adige      NaN     Pinot Grigio   

                          winery  
10              Borgo del Tiglio  
37                    Avignonesi  
38              Casina di Cornia  
39      Castello di Monterinaldi  
43                       Rignana  
...                          ...  
150824         Principessa Gavia  
150920                   Letrari  
150925     Feudi di San Gregorio  
150927                 Terredora  
150929             Alois Lageder  

[18122 rows x 11 columns]

In [142]:
df.loc[df.country.isin(['Italy','France','Germany'])]

Unnamed: 0 country                                        description  \
4                4  France  This is the top wine from La Bégude, named aft...   
10              10   Italy  Elegance, complexity and structure come togeth...   
13              13  France  This wine is in peak condition. The tannins an...   
18              18  France  Coming from a seven-acre vineyard named after ...   
32              32   Italy  Underbrush, scorched earth, menthol and plum s...   
...            ...     ...                                                ...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150926      150926  France  Offers an intriguing nose with ginger, lime an...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150928      150928  France  A perfect salmon shade, with scents of peaches...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

                    designation  points  price            province  \
4                    La Brûlade      95   66.0            Provence   
10           Ronco della Chiesa      95   80.0  Northeastern Italy   
13      Château Montus Prestige      95   90.0    Southwest France   
18                Le Pigeonnier      95  290.0    Southwest France   
32                Vigna Piaggia      90    NaN             Tuscany   
...                         ...     ...    ...                 ...   
150925                      NaN      91   20.0      Southern Italy   
150926           Cuvée Prestige      91   27.0           Champagne   
150927            Terre di Dora      91   20.0      Southern Italy   
150928          Grand Brut Rosé      90   52.0           Champagne   
150929                      NaN      90   15.0  Northeastern Italy   

                      region_1 region_2             variety  \
4                       Bandol      NaN  Provence red blend   
10                      Collio      NaN            Friulano   
13                     Madiran      NaN              Tannat   
18                      Cahors      NaN              Malbec   
32      Brunello di Montalcino      NaN          Sangiovese   
...                        ...      ...                 ...   
150925       Fiano di Avellino      NaN         White Blend   
150926               Champagne      NaN     Champagne Blend   
150927       Fiano di Avellino      NaN         White Blend   
150928               Champagne      NaN     Champagne Blend   
150929              Alto Adige      NaN        Pinot Grigio   

                       winery  
4        Domaine de la Bégude  
10           Borgo del Tiglio  
13          Vignobles Brumont  
18         Château Lagrézette  
32            Abbadia Ardenga  
...                       ...  
150925  Feudi di San Gregorio  
150926              H.Germain  
150927              Terredora  
150928                 Gosset  
150929          Alois Lageder  

[47028 rows x 11 columns]

In [146]:
df.loc[df.designation.notnull()]

Unnamed: 0 country                                        description  \
0                0      US  This tremendous 100% varietal wine hails from ...   
1                1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2                2      US  Mac Watson honors the memory of a wine once ma...   
3                3      US  This spent 20 months in 30% new French oak, an...   
4                4  France  This is the top wine from La Bégude, named aft...   
...            ...     ...                                                ...   
150923      150923  France  Rich and toasty, with tiny bubbles. The bouque...   
150924      150924  France  Really fine for a low-acid vintage, there's an...   
150926      150926  France  Offers an intriguing nose with ginger, lime an...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150928      150928  France  A perfect salmon shade, with scents of peaches...   

                                 designation  points  price        province  \
0                          Martha's Vineyard      96  235.0      California   
1       Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2              Special Selected Late Harvest      96   90.0      California   
3                                    Reserve      96   65.0          Oregon   
4                                 La Brûlade      95   66.0        Provence   
...                                      ...     ...    ...             ...   
150923                              Demi-Sec      91   30.0       Champagne   
150924                          Diamant Bleu      91   70.0       Champagne   
150926                        Cuvée Prestige      91   27.0       Champagne   
150927                         Terre di Dora      91   20.0  Southern Italy   
150928                       Grand Brut Rosé      90   52.0       Champagne   

                 region_1           region_2             variety  \
0             Napa Valley               Napa  Cabernet Sauvignon   
1                    Toro                NaN       Tinta de Toro   
2          Knights Valley             Sonoma     Sauvignon Blanc   
3       Willamette Valley  Willamette Valley          Pinot Noir   
4                  Bandol                NaN  Provence red blend   
...                   ...                ...                 ...   
150923          Champagne                NaN     Champagne Blend   
150924          Champagne                NaN     Champagne Blend   
150926          Champagne                NaN     Champagne Blend   
150927  Fiano di Avellino                NaN         White Blend   
150928          Champagne                NaN     Champagne Blend   

                         winery  
0                         Heitz  
1       Bodega Carmen Rodríguez  
2                      Macauley  
3                         Ponzi  
4          Domaine de la Bégude  
...                         ...  
150923                 Jacquart  
150924  Heidsieck & Co Monopole  
150926                H.Germain  
150927                Terredora  
150928                   Gosset  

[105195 rows x 11 columns]

### Summay functions and Maps apply

In [147]:
df = pd.read_csv('winemag-data_first150k.csv')

In [148]:
df.head()

Unnamed: 0 country                                        description  \
0           0      US  This tremendous 100% varietal wine hails from ...   
1           1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2           2      US  Mac Watson honors the memory of a wine once ma...   
3           3      US  This spent 20 months in 30% new French oak, an...   
4           4  France  This is the top wine from La Bégude, named aft...   

                            designation  points  price        province  \
0                     Martha's Vineyard      96  235.0      California   
1  Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2         Special Selected Late Harvest      96   90.0      California   
3                               Reserve      96   65.0          Oregon   
4                            La Brûlade      95   66.0        Provence   

            region_1           region_2             variety  \
0        Napa Valley               Napa  Cabernet Sauvignon   
1               Toro                NaN       Tinta de Toro   
2     Knights Valley             Sonoma     Sauvignon Blanc   
3  Willamette Valley  Willamette Valley          Pinot Noir   
4             Bandol                NaN  Provence red blend   

                    winery  
0                    Heitz  
1  Bodega Carmen Rodríguez  
2                 Macauley  
3                    Ponzi  
4     Domaine de la Bégude

In [149]:
df.describe()

Unnamed: 0         points          price
count  150930.000000  150930.000000  137235.000000
mean    75464.500000      87.888418      33.131482
std     43569.882402       3.222392      36.322536
min         0.000000      80.000000       4.000000
25%     37732.250000      86.000000      16.000000
50%     75464.500000      88.000000      24.000000
75%    113196.750000      90.000000      40.000000
max    150929.000000     100.000000    2300.000000

In [150]:
df.points.describe()

count    150930.000000
mean         87.888418
std           3.222392
min          80.000000
25%          86.000000
50%          88.000000
75%          90.000000
max         100.000000
Name: points, dtype: float64

In [151]:
df.country.describe()

count     150925
unique        48
top           US
freq       62397
Name: country, dtype: object

In [154]:
df.points.max()
df.points.min()

80

In [155]:
df.country.unique()

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

In [158]:
df.country.value_counts()

US                        62397
Italy                     23478
France                    21098
Spain                      8268
Chile                      5816
Argentina                  5631
Portugal                   5322
Australia                  4957
New Zealand                3320
Austria                    3057
Germany                    2452
South Africa               2258
Greece                      884
Israel                      630
Hungary                     231
Canada                      196
Romania                     139
Slovenia                     94
Uruguay                      92
Croatia                      89
Bulgaria                     77
Moldova                      71
Mexico                       63
Turkey                       52
Georgia                      43
Lebanon                      37
Cyprus                       31
Brazil                       25
Macedonia                    16
Serbia                       14
Morocco                      12
England 

In [161]:
mean_value = df.points.mean()
print(mean_value)

87.8884184721394


In [162]:
df.points.map(lambda p:p-mean_value)

0         8.111582
1         8.111582
2         8.111582
3         8.111582
4         7.111582
            ...   
150925    3.111582
150926    3.111582
150927    3.111582
150928    2.111582
150929    2.111582
Name: points, Length: 150930, dtype: float64

In [164]:
def remean_points(row):
    row.points=row.points-mean_value
    return row
df.apply(remean_points, axis='columns')


Unnamed: 0 country                                        description  \
0                0      US  This tremendous 100% varietal wine hails from ...   
1                1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2                2      US  Mac Watson honors the memory of a wine once ma...   
3                3      US  This spent 20 months in 30% new French oak, an...   
4                4  France  This is the top wine from La Bégude, named aft...   
...            ...     ...                                                ...   
150925      150925   Italy  Many people feel Fiano represents southern Ita...   
150926      150926  France  Offers an intriguing nose with ginger, lime an...   
150927      150927   Italy  This classic example comes from a cru vineyard...   
150928      150928  France  A perfect salmon shade, with scents of peaches...   
150929      150929   Italy  More Pinot Grigios should taste like this. A r...   

                                 designation    points  price  \
0                          Martha's Vineyard  8.111582  235.0   
1       Carodorum Selección Especial Reserva  8.111582  110.0   
2              Special Selected Late Harvest  8.111582   90.0   
3                                    Reserve  8.111582   65.0   
4                                 La Brûlade  7.111582   66.0   
...                                      ...       ...    ...   
150925                                   NaN  3.111582   20.0   
150926                        Cuvée Prestige  3.111582   27.0   
150927                         Terre di Dora  3.111582   20.0   
150928                       Grand Brut Rosé  2.111582   52.0   
150929                                   NaN  2.111582   15.0   

                  province           region_1           region_2  \
0               California        Napa Valley               Napa   
1           Northern Spain               Toro                NaN   
2               California     Knights Valley             Sonoma   
3                   Oregon  Willamette Valley  Willamette Valley   
4                 Provence             Bandol                NaN   
...                    ...                ...                ...   
150925      Southern Italy  Fiano di Avellino                NaN   
150926           Champagne          Champagne                NaN   
150927      Southern Italy  Fiano di Avellino                NaN   
150928           Champagne          Champagne                NaN   
150929  Northeastern Italy         Alto Adige                NaN   

                   variety                   winery  
0       Cabernet Sauvignon                    Heitz  
1            Tinta de Toro  Bodega Carmen Rodríguez  
2          Sauvignon Blanc                 Macauley  
3               Pinot Noir                    Ponzi  
4       Provence red blend     Domaine de la Bégude  
...                    ...                      ...  
150925         White Blend    Feudi di San Gregorio  
150926     Champagne Blend                H.Germain  
150927         White Blend                Terredora  
150928     Champagne Blend                   Gosset  
150929        Pinot Grigio            Alois Lageder  

[150930 rows x 11 columns]

### Datatypes and missing values

In [165]:
df.price.dtype

dtype('float64')

In [166]:
df.dtypes

Unnamed: 0       int64
country         object
description     object
designation     object
points           int64
price          float64
province        object
region_1        object
region_2        object
variety         object
winery          object
dtype: object

In [173]:
df.loc[pd.isnull(df.country)]

Unnamed: 0 country                                        description  \
1133          1133     NaN  Delicate white flowers and a spin of lemon pee...   
1440          1440     NaN  A blend of 60% Syrah, 30% Cabernet Sauvignon a...   
68226        68226     NaN  From first sniff to last, the nose never makes...   
113016      113016     NaN  From first sniff to last, the nose never makes...   
135696      135696     NaN  From first sniff to last, the nose never makes...   

         designation  points  price province region_1 region_2     variety  \
1133       Askitikos      90   17.0    ankit      NaN      NaN   Assyrtiko   
1440            Shah      90   30.0    ankit      NaN      NaN   Red Blend   
68226   Piedra Feliz      81   15.0    ankit      NaN      NaN  Pinot Noir   
113016  Piedra Feliz      81   15.0    ankit      NaN      NaN  Pinot Noir   
135696  Piedra Feliz      81   15.0    ankit      NaN      NaN  Pinot Noir   

           winery  
1133     Tsililis  
1440    Büyülübağ  
68226     Chilcas  
113016    Chilcas  
135696    Chilcas

In [172]:
df.province =  df.province.fillna("ankit")

In [174]:
pd.isnull(df.region_2)

0         False
1          True
2         False
3         False
4          True
          ...  
150925     True
150926     True
150927     True
150928     True
150929     True
Name: region_2, Length: 150930, dtype: bool

In [177]:
pd.isnull(df.region_2).value_counts()

True     89977
False    60953
Name: region_2, dtype: int64

In [178]:
df.country.replace('US', 'India')

0          India
1          Spain
2          India
3          India
4         France
           ...  
150925     Italy
150926    France
150927     Italy
150928    France
150929     Italy
Name: country, Length: 150930, dtype: object